### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
> Sounds good. Hopefully that runtime doesn't include SDL regressions eyes

Hopefully not. :-) Feel free to test and merge.

**Comment by necessarily-equal** [comment]
Quick testing seems to show this works.

**Comment by AsciiWolf** [comment]
Can I merge the PR? :-)

**Comment by illwieckz** [comment]
Sorry I just discover the PR.

**Pull request merged**
